### ISSUE TITLE
Node fails to start due to corrupt database

### ISSUE THREAD

**Issue by hurlenko** [bitprim/bitprim-insight#223]
After reading [this](https://github.com/libbitcoin/libbitcoin-server/issues/405), [this](https://github.com/libbitcoin/libbitcoin-server/issues/413#issuecomment-345380130), and [this](https://github.com/libbitcoin/libbitcoin-server/wiki/Frequently-Asked-Questions#q-what-sort-of-failure-will-corrupt-the-store) I believe this more related to libbitcoin. Just wanted to know how can one recover from such a failure without resyncing the full blockchain. Is there a way to resync only the corrupt data?

<details>
 <summary>Log output:</summary>

```
bitprim_1  | 2018-12-20T07:07:47.046089 DEBUG [node] ================= startup  ==================
bitprim_1  | 2018-12-20T07:07:47.046288 INFO [node] ================= startup  ==================
bitprim_1  | 2018-12-20T07:07:47.046390 WARNING [node] ================= startup  ==================
bitprim_1  | 2018-12-20T07:07:47.046450 ERROR [node] ================= startup  ==================
bitprim_1  | 2018-12-20T07:07:47.046470 FATAL [node] ================= startup  ==================
bitprim_1  | 2018-12-20T07:07:47.046390 WARNING [node] ================= startup  ==================
bitprim_1  | 2018-12-20T07:07:47.046450 ERROR [node] ================= startup  ==================
bitprim_1  | 2018-12-20T07:07:47.046470 FATAL [node] ================= startup  ==================
bitprim_1  | 2018-12-20T07:07:47.046489 INFO [node] Using config file: "/app/bitprim-restapi.cfg"
bitprim_1  | 2018-12-20T07:07:47.046513 INFO [node] Node version: 0.17.0
bitprim_1  | 2018-12-20T07:07:47.046528 INFO [node] Currency: BCH - Bitcoin Cash
bitprim_1  | 2018-12-20T07:07:47.046547 INFO [node] Keoken protocol enabled
bitprim_1  | 2018-12-20T07:07:47.046560 INFO [node] Compiled for microarchitecture: x86-64
bitprim_1  | 2018-12-20T07:07:47.046575 INFO [node] Network: Mainnet (3908297187)
bitprim_1  | 2018-12-20T07:07:47.046658 INFO [node] Configured to use 4 cores
bitprim_1  | 2018-12-20T07:07:47.046718 INFO [node] Press CTRL-C to stop the node.
bitprim_1  | 2018-12-20T07:07:47.046732 INFO [node] Please wait while the node is starting...
bitprim_1  | 2018-12-20T07:07:47.046862 DEBUG [database] Buckets: block [650000], transaction [110000000], spend [250000000], history [107000000]
bitprim_1  | 2018-12-20T07:07:47.047305 ERROR [node] Failure starting blockchain.
bitprim_1  | 2018-12-20T07:07:47.047305 ERROR [node] Failure starting blockchain.
bitprim_1  | 2018-12-20T07:07:47.047344 ERROR [node] Node failed to start with error, operation failed.
bitprim_1  | 2018-12-20T07:07:47.047344 ERROR [node] Node failed to start with error, operation failed.
bitprim_1  | Application startup exception: System.ApplicationException: Executor::InitAndRunAsync failed; error code: 2
bitprim_1  |    at bitprim.insight.Startup.StartFullNode(IServiceCollection services, ServiceProvider serviceProvider) in /app/bitprim-insight/bitprim.insight/Startup.cs:line 252
bitprim_1  | --- End of stack trace from previous location where exception was thrown ---
bitprim_1  |    at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
bitprim_1  |    at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
bitprim_1  |    at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
bitprim_1  | [2018-12-20 07:07:47 ] FTL         Application startup exception
bitprim_1  | System.ApplicationException: Executor::InitAndRunAsync failed; error code: 2
bitprim_1  |    at bitprim.insight.Startup.StartFullNode(IServiceCollection services, ServiceProvider serviceProvider) in /app/bitprim-insight/bitprim.insight/Startup.cs:line 252
bitprim_1  | --- End of stack trace from previous location where exception was thrown ---
bitprim_1  |    at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
bitprim_1  |    at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
bitprim_1  |    at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
bitprim_1  | [2018-12-20 07:07:47 ] FTL         Host terminated unexpectedly
bitprim_1  | System.ApplicationException: Executor::InitAndRunAsync failed; error code: 2
bitprim_1  |    at bitprim.insight.Startup.StartFullNode(IServiceCollection services, ServiceProvider serviceProvider) in /app/bitprim-insight/bitprim.insight/Startup.cs:line 252
bitprim_1  | --- End of stack trace from previous location where exception was thrown ---
bitprim_1  |    at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
bitprim_1  |    at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
bitprim_1  |    at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
bitprim_1  |    at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
bitprim_1  |    at bitprim.insight.Program.Main(String[] args) in /app/bitprim-insight/bitprim.insight/Program.cs:line 20
```
</details>

**Comment by dario-ramos** [comment]
Hi, did you try deleting the lock files inside your database directory? They are called `flush_lock` and `exclusive lock`. If after that it still does not sync, the store is actually corrupt and you will need to resync from scratch.
    To lower the chance s of this happening, set `flush_writes = true` in your cfg file after completing IBD.
    This issue is indeed inherited from libbitcoin; we currently have a fix for it in our upcoming release, 0.18.0, so we'll keep you posted.

**Comment by hurlenko** [comment]
Hi @dario-ramos, I already have `flush_writes = true` in my config. I didn't try deleting those files but I will if it happens again (hope it won't). Thanks!
